---
  - name: Find existing instance(s)
    hosts: "tag_Name_ami-build"
    gather_facts: false
    tags: find
    tasks:
      - name: Add to old-ami-build group
        group_by:
          key: old-ami-build

  - hosts: control
    connection: local
    gather_facts: no
    roles:
      - luanch_ec2_instance
#install nginx on my luanched instances
  - hosts: template_ami
    roles:
      - nginx

  - hosts: control
    connection: local
    gather_facts: no
    roles:
      - create_ami
      - luanch_config
      - lb
      - asg

  - hosts: old-ami-build
    roles:
      - terminate_instance
