---
  - hosts: control
    connection: local
    gather_facts: no
    roles:
      - luanch_ec2_instance
#install nginx on my luanched instances
  - hosts: template_ami
    roles:
      - nginx

  - hosts: control
    connection: local
    gather_facts: no
    roles:
      - create_ami
      - luanch_config
      - lb

  - hosts: template_ami
    roles:
      - terminate_instance
