---
  - hosts: control
    connection: local
    gather_facts: no
    roles:
      - luanch_ec2_instance
#install nginx on my luanched instances
  - hosts: template_ami
    roles:
      - nginx

  - hosts: control
    connection: local
    gather_facts: no
    roles:
      - create_ami

  - hosts: old-ami-build
    roles:
      - terminate_instance
